### ISSUE TITLE
Select на открывается на мобилках.

### ISSUE THREAD

**Issue by dramoturg** [ange007/JQueryFormStyler-Modern#11]
Не открывается на мобилках выпадающих список у select.

**Comment by ange007** [comment]
А в оригинально

**Comment by dramoturg** [comment]
В оригинальной версии не открывается.

**Comment by ange007** [comment]
Значит нужно смотреть.
А о каких мобилках речь?

**Comment by dramoturg** [comment]
Эмуляция в гугл хроме. Iphone 4. Ipad 2

**Comment by ange007** [comment]
@dramoturg, зачем закрывать задачу - если присутствует баг который нужно проверять и исправлять?

**Comment by dramoturg** [comment]
Извини не на ту кнопку нажал.

**Comment by dramoturg** [comment]
Разобрался это не бага а фича. стилизованный дропдаун специально не показывается так как выводится нативный контрол телефона.

**Comment by ange007** [comment]
Ну да, есть такое.
