### ISSUE TITLE
А будет этот плагин зарегистрирован в bower?

### ISSUE THREAD

**Issue by vaeum** [ange007/JQueryFormStyler-Modern#19]
Или нет?

**Comment by ange007** [comment]
Будет, нужно только разобраться как это сделать :)

**Comment by vaeum** [comment]
Советую прочитать 
http://nano.sapegin.ru/all/bower

**Comment by ange007** [comment]
Благодарю, почитаю

**Comment by ange007** [comment]
Репозиторий то я добавил в **bower**, только вот пока-что это чёрти-что.
Билды я ведь не заливаю в рабочую ветку, так как это не имеет особого смысла.
Буду думать как это решить.

Жаль что нельзя в качестве источника указать **GitHub Releases** *(по крайней мере не нашёл как это сделать)*.

**Comment by vaeum** [comment]
там же идет по тегам, в этой репе они есть я видел

**Comment by ange007** [comment]
Да, добавить то я добавил *( правда у меня не находит почему-то через сайт )*. 
Но там ведь скачивается полностью содержимое бранча/тега, а у меня там нету скомпилированных файлов *( только в gh-pages, но как направить bower туда - я не знаю )*, а так всё в **GitHub Releases**.

**Comment by vaeum** [comment]
ну так просто создайте папку dist и кладите скомпилированные файлы туда
и нужно добавить секцию main в bower.json
это для сборщиков проектов

**Comment by ange007** [comment]
Только в таком случае те кто делает коммит для дев.версии - должен будет и загружать скомпилированную версию. Это не очень удобно. 
Но судя по всему это единственный вариант на данный момент.

**Comment by ange007** [comment]
Сделал финт ушами.
Реализовал автосборку в ветку release и сделал её веткой по умолчанию.
Сейчас буду проверять как оно работает в bower

**Comment by ange007** [comment]
Думаю реализовать такой алгоритм, не знаю правда выйдет ли нормально.
1. Я создал ветку "release"
2. В неё уже происходит автосборка и коммит при помощи Travis
3. Научу Travis при коммите в stable - создавать тег для ветки release
4. Профит

**Comment by vaeum** [comment]
звучит хорошо, главное чтоб Bower подхватил,

**Comment by ange007** [comment]
Вроде всё сделал, только правда получается что компоненты в папке build, хотя в bower.json описан блок main. 
Я думал он должен брать только нужные файлы.

**Comment by ange007** [comment]
Всё, вроде сделал более-менее нормально.
Так что задачу на данный момент закрываю.
