### ISSUE TITLE
[enhancement] Скорость подсчета ширины на больших списках и ошибки плейсхолдера в селекте

### ISSUE THREAD

**Issue by pafnuty** [ange007/JQueryFormStyler-Modern#2]
Пишу, что бы не забыть перенести последние правки из пулреквестов оригинала: 
- [x] https://github.com/Dimox/jQueryFormStyler/pull/95
- [x] https://github.com/Dimox/jQueryFormStyler/pull/94

**Comment by ange007** [comment]
Ну данные правки внесены в код практически сразу после создания форка.
Или нужно чтоб их создатель перенёс сам?

**Comment by pafnuty** [comment]
Я почему то думал, что не внесены, хотел внести, но времени не нашлось, записал чтобы не забыть. 
Тогда тиккет не актуален.
