### ISSUE TITLE
[feature request] selectDropUpOffset и selectDropDownOffset

### ISSUE THREAD

**Issue by pafnuty** [ange007/JQueryFormStyler-Modern#28]
Иногда бывает так, что на сайте есть фиксированная шапка или подвал.
В этом случае при открытии длинного селекта есть вероятность, что мы никогда не сможем увидеть первый или последний пункт селекта (особенно актуально это на мобильнике, если убрать проверку на андроид, всё прекрасно работает)

P.S. Локально у себя реализовал, создаю тиккет, что бы не забыть сделать PR

**Comment by pafnuty** [comment]
CR-4071

**Comment by ange007** [comment]
Так как никакого движения по данному вопросу нет. 
И я не совсем понимаю что к чему - пока закрываю.
