### ISSUE TITLE
[docs] Изменение расположения демо

### ISSUE THREAD

**Issue by pafnuty** [ange007/JQueryFormStyler-Modern#29]
@ange007 
С недавнего времени на гитхабе появилась возможность создавать страницы из папки docs http://i.imgur.com/m4jztaJ.png возможно это упростит процесс сборки и избавит от проблемы с путями на локальной машине (сейчас ссылки на собранные стили и скрипты смотрят не туда)?

**Comment by ange007** [comment]
Спасибо, посмотрю.

**Comment by ange007** [comment]
Что-то как-то не получается перенести туда.
Вроде в настройках выбрал - использоваться docs - но исходники лежат старые, как и были.

**Comment by ange007** [comment]
Уже получилось. 
Только вот лучше не стало )) доступа ведь к js и css всё-равно нету.

**Comment by ange007** [comment]
Реализовал смену пути к файлам при помощи Travis-CI в момент сборки страницы с примерами, так что на данный момент проблем с путями быть не должно.
