### ISSUE TITLE
Стиль кода в JS

### ISSUE THREAD

**Issue by pafnuty** [ange007/JQueryFormStyler-Modern#3]
Заметил довольно необычный (очень редко встречаю такой) стиль написания кода в js плагина, так задумано?

**Comment by ange007** [comment]
Ну собственно да.
Стиль "наработан на работе".

Вам он кажется не удобным? Готов выслушать идеи и пожелания.

**Comment by pafnuty** [comment]
Мне он показался взятым из php :smile:, т.к. обычно в php расставляют пробелы между первым и последним параметрами в функциях и т.п.
Вопрос форматирования js - довольно холиварная тема, но если у вас так принято, то остальные должны так же принять это форматирование, иначе будет каша.
Обычно разработчики используют инструменты автоформатирования, как правило, с настройками по умолчанию или мелкими доводками, ваш стиль просто сильно отличается от дефолтного.

Создал pr https://github.com/ange007/JQueryFormStyler-Modern/pull/4, но добиться настройками полного соответствия не удалось. в некоторых местах есть расхождения.

**Comment by ange007** [comment]
Ну я в итоге такое написание использую везде, и в PHP, и в JS, и даже в Delphi/Pascal.
Мне кажется код более удобно читать, особенно что касается очень больших JS проектов

**Comment by pafnuty** [comment]
С большими js проектами работать не приходилось, не те скиллы :smile: 
В любом случае в продакшн попадает сжатая версия, а для использования в проектах никто не мешает отформатировать код так, как требуется или требуют руководящие инструкции.
