### ISSUE TITLE
Новый формат настроек и проекта

### ISSUE THREAD

**Issue by ange007** [ange007/JQueryFormStyler-Modern#37]
Думаю сделать настройки в древовидном формате:
```javascript
defaults = {
	select: {
		triggerHTML: '<div class="jq-selectbox__trigger-arrow"></div>',
		search: {
			limit: 10,
			remote: {
				active: false,
				method: 'GET',
				url: 'http://www.google.com/',
				data: '',
				onSuccess: function( ) { },
				onError: function( ) { },
			} 
		},
		visibleOptions: 0,
		smartPosition: 0,
		onOpened: function( ) { },
		onClosed: function( ) { },
	},
	checkbox: {
		indeterminate: false,
	},
	password: {
		switchHTML: '<button type="button" class="' + pluginName + '"></button>',
	}
	...
}
```
Будет ли нормально?

**Comment by yunusga** [comment]
Будет отлично.. Код-стайл для проекта точно надо подправить, сейчас всё как то размазано совсем.

**Comment by ange007** [comment]
А как быть с обновлением структуры для тех кто уже скачал библиотеку?
Таких то не много, всего человек 5, но всё-же.
Делать мажорное обновление? Или и в основной ветке пойдёт?

**Comment by yunusga** [comment]
Да, думаю лучше сделать мажорное обновление

**Comment by ange007** [comment]
Залил в dev ветку версию с новым форматом настроек.

**Comment by ange007** [comment]
Залил новое обновление. Разбил компоненты на "классы".
