### ISSUE TITLE
В IE11 не верно работает "умное позиционирование" или расчёт минимальной высоты

### ISSUE THREAD

**Issue by ange007** [ange007/JQueryFormStyler-Modern#46]
В IE11 не верно работает "умное позиционирование" или расчёт минимальной высоты.
При малом остатке высоты для раскрытия списка вниз - список не отображается как надо.
В оригинальном плагине такого нет.

**Comment by yunusga** [comment]
[github.com/ange007/JQueryFormStyler-Modern/pull/48](https://github.com/ange007/JQueryFormStyler-Modern/pull/48)
