### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by yunusga** [ange007/JQueryFormStyler-Modern#47]
Необходима инструкция участия в разработке плагина, а то сложно сходу разобрать что? где? когда? и из какой ветки

**Comment by ange007** [comment]
Что там следует описать помимо назначения веток?

**Comment by yunusga** [comment]
Если нет никаких других особенностей, то хватит и описания о ветках, что и где лежит

**Comment by ange007** [comment]
Добавил.
