### ISSUE TITLE
Почему в оригинальном компоненте присутствует необходимость в trigger('refresh')?

### ISSUE THREAD

**Issue by ange007** [ange007/JQueryFormStyler-Modern#6]
Возможно кто-то знает ответ на данный вопрос?

Я правда ещё совсем не вникал  в данный вопрос, но есть такое ощущение что обработка изменения состояния через $( original ).on( 'change' ) - не вызвала бы большой нагрузки.

**Comment by pafnuty** [comment]
.trigger('refresh') для простых пользователей гораздо проще, чем прописываение переинициализации плаина вручную.
Думаю в этом триггере смущеает то, что обычно делают по-другому.
типа `$('.styler').styler('refresh');`

**Comment by ange007** [comment]
Нет, я немного о другом.
Почему используется вызов trigger( 'refresh' ), если можно просто в плагине обрабатывать события изменения состояния.

**Comment by pafnuty** [comment]
Ну например как отследить изменение кол-ва пунтков в селекта или кол-ва чекбоксов на странице?
Суть этого метода именно в ручной переинициализации плагина, когда это нужно.

**Comment by ange007** [comment]
Ну тут больше вопрос в необходимости .trigger('refresh') при изменении состояния input:checkbox|radio

**Comment by pafnuty** [comment]
Я уже довольно давно не использовал стлизацию этих инпутов через плагин. Вполне хватает css, одновременно убирается проблема с этим триггером. 
Думаю для тех, кому не нужна стилизация этих инпутов через плагин не составит труда собрать для себя кастомный скрипт, благо gulp это пзволяет :smile: А те, кто стилизует — смирятся с необходимостью ручной переинициализации, когда это нужно.
