### ISSUE TITLE
Разделение каркасных стилей и стилей оформления

### ISSUE THREAD

**Issue by ange007** [ange007/JQueryFormStyler-Modern#8]
Нужно реализовать разделение стилей "каркаса" и оформления, чтоб можно было удобнее и быстрее менять оформление контролов.

**Comment by ange007** [comment]
В каком виде лучше делать разделение?
Разделить по файлам, и при сборке - вначале выводить стили а ниже каркасы?

**Comment by vaeum** [comment]
думаю каркас лучше выводить в начале, а стили после это нужно чтоб перебить стили каркаса, или сделать как у бутстрапа,  файл с темой

**Comment by ange007** [comment]
Ну тут смотря что именно подразумевать под каркасом. Во вчерашней версии я просто разделил всё что связано со стилизацией ( background, color, border ), и всё что связано с базой ( размеры, отступления и т.д. ).

Поэтому в данном случае перекрытия ведь никакого нет.

**Comment by vaeum** [comment]
но если пользователю понадобиться в теме менять размеры и прочие настройки каркаса
в моем понимании каркас это то без чего стили инпутов просто развалятся
например если убрать position absolute у выпадающего списка

**Comment by ange007** [comment]
Ну если ему это понадобиться то это ведь не проблема сделать.
Другое дело когда в проекте нужно просто быстро поменять обводку, фон, цвет шрифта *( это то что по большей части и меняют )*.

Или как лучше делать?
Просто опять таки - чтоб не получилось что от каркаса остаётся по 2-3 параметра, а всё остальное считается стилизацией **( в таком случае это не имеет вообще никакого смысла )**.

**Comment by vaeum** [comment]
либо сделать так, сначала сделать каркас и дефолтную тему, а следом идет файл с темой

**Comment by vaeum** [comment]
и если будет выбран этот вариант, попрошу сделать беграунды у стандартной темы просто цветом, а не как в оригинальном плагине через base64, а то я от проекта в проект их выпиливаю

**Comment by ange007** [comment]
Нужно подумать. 
Пока доделаю в том виде как я начал + разделю в исходнике.

Просто делать 2 файла для jquery плагина, когда в основном люди не занимаются сборкой а просто используют собранные... 
Мне кажется от этого будет только вред.

**Comment by vaeum** [comment]
Да делайте так как задумано, может позже идею интересная будет

**Comment by ange007** [comment]
Залил версию с первой попыткой разделения на каркас и темы.

**Comment by ange007** [comment]
Продолжается работа в данном направлении.
